### ISSUE TITLE
Colour?

### ISSUE THREAD

**Issue by EhsanMomeni81** [PoOwAa/MMM-network-signal#1]
Hi,

Is it possible to get the WiFi signal in colour?

**Comment by PoOwAa** [comment]
Hi,

At the moment you have to override the CSS rules, which are in MMM-network-signal.css

You are looking for border-top-color properties. #aaa and rgba(68,68,68,0.4)

In next version I probably will implement the colour via config file. :)

**Comment by EhsanMomeni81** [comment]
Great. Thank you so much

**Comment by mcnahum** [comment]
Thanks, I'm looking for color too, but in fact I don't care of the power just to know if it's connected or not (visually)

**Comment by PoOwAa** [comment]
@mcnahum actually you can just simply modify the thresholds configuration to something unbelievable high something like this:

`thresholds: {
   strong: 100000,
   medium: 100001,
  weak: 100002
}`

You'll see all the time the "strong" signal this way.
