### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by Mert4531** [PoOwAa/MMM-network-signal#13]
Hi there;

I wanna decrease icon size smaller than original size. How can i do that. Also I want to change module position bottom_left or bottom_right. 

Actually I wanna put that module bottom edge. Please help me about fix this issue

**Comment by ArnoStrasbourg** [comment]
Icon size, in /home/pi/MagicMirror/modules/MMM-network-signal, the MMM-network-signal.js, you can change the size at the line 47 : 
wifiSign.style = "transform:scale(0.45)";

Positionning, in the module configuration, just add : position: "bottom_left",

**Comment by robertybob** [comment]
![FC647037-012C-443B-81EF-42407233AF49](https://user-images.githubusercontent.com/2610395/89104658-da963b80-d412-11ea-95cd-450027ea753a.png)

@ArnoStrasbourg @PoOwAa This is positioned bottom_right , along worth the module above, however the icon is not aligned to the right. Is this possible to do?

**Comment by ArnoStrasbourg** [comment]
I don't really know as I'm not the conceptor of the module. But, I think it is possible to touch the CSS file to do that.

**Comment by PoOwAa** [comment]
I just noticed a new fork, that maybe contains this fix in this repo:

https://github.com/zbattenfield/MMM-network-signal

I hope he/she will create a PR! ^^

@scm04, @zbattenfield I really appreciate if you create a PR! :)

**Comment by scm04** [comment]
@PoOwAa sure thing! I just created  PR #24 with those changes.

**Comment by PoOwAa** [comment]
Thanks @scm04 !
