### ISSUE TITLE
Consider transparent images and text with no predefined background

### ISSUE THREAD

**Issue by RomanOnARiver** [PoOwAa/MMM-network-signal#14]
The images representing the network speed (and maybe the optional text label "showMessage" but I'm not using that so I don't know) have a hardcoded black background to them, consider not having any background at all, to fit better with those who may be using for example an image slideshow or even just a different color background. Attached is an example of what I mean - I have the signal in the top_right and the background is from a photo slideshow 
![noMessage](https://user-images.githubusercontent.com/62953602/78051764-298c7100-734c-11ea-95af-9289075e7776.jpg)

**Comment by PoOwAa** [comment]
That's because the icons changed from CSS rules to static images. We should remove the background color. Thanks for the tip!
