### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ArnoStrasbourg** [PoOwAa/MMM-network-signal#16]
Hi,

I installed the module, made `npm i` in the module directory and `git pull && npm install` in the MagicMirror directory too.

Unfortunatly,  I have a black screen.

do you have any idea about this problem ?

Thanks.

**Comment by muertopollo** [comment]
Did you set the configuration options in config.js ???
Unlike every other MMM module, they're not pre-configured for you.

**Comment by ArnoStrasbourg** [comment]
Yes of course, here is my config :
`            {
			module: "MMM-network-signal",
			position: "top_left",
			config: {
				updateInterval: 5000,
				maxTimeout: 1000,
				server: "8.8.8.8",
				thresholds: 150,
				showMessage: true
			}
		},`

I juste start with a fresh install of MM. Problem is same.
Thank you for answer.

**Comment by ArnoStrasbourg** [comment]
I found my problem. It was a bug from another module.
Now it's fix.
