### ISSUE TITLE
Module breaks config

### ISSUE THREAD

**Issue by nickdelaserda** [PoOwAa/MMM-network-signal#2]
After installing module and setting up in config.js, module doesnt work and breaks the config

**Comment by PoOwAa** [comment]
Please could you share your config? Do you have any error messages?

**Comment by ImTheBadWolf** [comment]
It does not break the config. Instead of this `{
    {
        module: "MMM-network-signal",
        position: "bottom_right",
    },
}`

Paste this to your config:
`{
        module: "MMM-network-signal",
        position: "bottom_right",
    },`

**Comment by Heinz-Beans** [comment]
It does not break the config. 
Instead of this:              
```
{                
    {            
        module: "MMM-network-signal",  
        position: "bottom_right",  
    },  
}
```

Paste just this to your config:  
```
{  
     module: "MMM-network-signal",  
     position: "bottom_right",  
},
```

**Comment by TDMPro2K** [comment]
I have just updated to mm 2.6 and the latest Rip version. I have just installed this module but ill I get now is a black screen. If I remove the module from loading the mirror is fine.. 
Do you know what could cause this?. P.s It was fine with the old build, only happened since I have updated.

**Comment by TDMPro2K** [comment]
So as always, as soon as I posted a issue I get it working. But for any of you that have it. go to
MagicMirror  folder and run: git pull && npm install
I must put something back in that is either overwritten or not updated during the update.
