### ISSUE TITLE
Feature request: optional reconnect if connection drop

### ISSUE THREAD

**Issue by mcnahum** [PoOwAa/MMM-network-signal#3]
I didn't found the good way to do it... but if you detect that there is no more network to try to reconnect to it ...

**Comment by PoOwAa** [comment]
I don't think this module should care about this.

If you're using raspberry or any other linux behind the mirror, you can setup another script, which is checking the internet connection.

On the raspberry forum I found this:

https://www.raspberrypi.org/forums/viewtopic.php?t=16054
