### ISSUE TITLE
top_right icon/status overlap

### ISSUE THREAD

**Issue by hkblock** [PoOwAa/MMM-network-signal#6]
In top_right region the status message overlaps with the icon instead of being next to the icon. Nothing else is in that region. The region in question should have what space it needs – the only other thing on top is the clock in the top_left.

**Comment by PoOwAa** [comment]
@ferferga can you check this, please?

**Comment by PierreLeoFerreira** [comment]
Seem to be having the same problem. Also unable to disable the status message.

**Comment by ferferga** [comment]
Let me take a look this weekend

**Comment by ferferga** [comment]
Fixed in #12
