### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kd4pba** [PoOwAa/MMM-network-signal#8]
Finding the instructions ambiguous. 

Where do the listed options go?  In the config?  Application does not appear to run with null values.

**Comment by PoOwAa** [comment]
Module has default configuration, so you should put only the configs what you want to change.

Every magic mirror modules should have the same pattern about configuration, like mentioned in the original documentation: https://github.com/MichMich/MagicMirror#configuration

So in your `MagicMirror/config/config.js` you have something like that:

```
{
    module: "MMM-network-signal",
    position: "bottom_right",
    config: {
        // Configuration of the module goes here.
    }
}
```

I'll update the readme about it.
